seed = 7
patience = 16
n_epochs = -1
causal = false
batch_size = 1024
context_size = 96

[model]
d_main = 256
context_dropout = 0.196553147863142
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.5155314711535162
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 4.255219097794737e-05
weight_decay = 0.0001364345910213009

[data]
seed = 0
path = ":data/weather"
cache = true
split = "random-2"
num_policy = "noisy-quantile"
