seed = 0

[model]
iterations = 4000
early_stopping_rounds = 3999
od_pval = 0.001
bagging_temperature = 0.2632243146305454
depth = 10
l2_leaf_reg = 3.1353759508497734
leaf_estimation_iterations = 3
learning_rate = 0.014610851679863828
task_type = "CPU"
thread_count = 4

[fit]
logging_level = "Verbose"

[data]
seed = 0
path = ":data/delivery-eta"
cache = true
split = "default"
cat_policy = "ordinal"
