seed = 14
patience = 16
n_epochs = -1
causal = false
batch_size = 256
context_size = 96

[model]
d_main = 128
context_dropout = 0.5882219647950191
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.07825025419431036
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 2.3977457529744578e-05
weight_decay = 2.561081360977117e-06

[data]
seed = 0
path = ":data/sberbank-housing"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
