seed = 7
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 512
dropout = 0.6654890055837697

[optimizer]
type = "AdamW"
lr = 0.00016834488991759595
weight_decay = 1.6636556796657439e-06

[data]
seed = 0
path = ":data/delivery-eta"
cache = true
split = "random-2"
cat_policy = "ordinal"
num_policy = "identity"
