seed = 10

[model]
iterations = 4000
early_stopping_rounds = 3999
od_pval = 0.001
bagging_temperature = 0.15665315288779919
depth = 11
l2_leaf_reg = 4.046761439080644
leaf_estimation_iterations = 9
learning_rate = 0.036516780212081705
task_type = "CPU"
thread_count = 4

[fit]
logging_level = "Verbose"

[data]
seed = 0
path = ":data/weather"
cache = true
split = "default"
