seed = 12

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.6516003449770659
gamma = 0.17208948364833782
lambda = 0.0
learning_rate = 0.0061700612734405
max_depth = 12
min_child_weight = 24.471768415521147
subsample = 0.6156829346845564

[fit]
verbose = true

[data]
seed = 0
path = ":data/homecredit-default"
cache = true
split = "random-2"
cat_policy = "ordinal"
