seed = 2
patience = 16
n_epochs = -1
causal = true
batch_size = 256
context_size = 96

[model]
d_main = 128
context_dropout = 0.0
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.0
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 0.000137832269311765
weight_decay = 0.00041013438224115365

[data]
seed = 0
path = ":data/sberbank-housing"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
