seed = 2

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.5637053342675156
gamma = 1.7669643952638894
lambda = 0.1380432648731945
learning_rate = 0.006510301000613239
max_depth = 8
min_child_weight = 0.0018188320231232403
subsample = 0.8118049391234415

[fit]
verbose = true

[data]
seed = 0
path = ":data/delivery-eta"
cache = true
split = "sliding-window-1"
cat_policy = "ordinal"
