seed = 0
patience = 16
n_epochs = -1
batch_size = 1024

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 128
d_embedding = 2
frequency_init_scale = 0.03430811721912205
lite = false

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 2048
dropout = 0.2339727530298089

[optimizer]
type = "AdamW"
lr = 1.8466677039144734e-05
weight_decay = 0.0002698802919704856

[data]
seed = 0
path = ":data/maps-routing"
cache = true
split = "sliding-window-1"
cat_policy = "ordinal"
num_policy = "identity"
