seed = 2
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "ResNet"
n_blocks = 3
d_block = 256
d_hidden_multiplier = 2
dropout1 = 0.48649175657928556
dropout2 = 0.0

[optimizer]
type = "AdamW"
lr = 0.00026856915557520926
weight_decay = 4.4031333305642505e-05

[data]
seed = 0
path = ":data/homecredit-default"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
