seed = 0
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 1024
dropout = 0.6969758780370328

[optimizer]
type = "AdamW"
lr = 3.1948512335448785e-05
weight_decay = 2.1593448004458202e-06

[data]
seed = 0
path = ":data/homecredit-default"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
