seed = 8
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 512
dropout = 0.2046595560368715

[optimizer]
type = "AdamW"
lr = 0.0005115311727713176
weight_decay = 2.03403772106718e-06

[data]
seed = 0
path = ":data/weather"
cache = true
split = "sliding-window-2"
num_policy = "noisy-quantile"
