seed = 1
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 128
dropout = 0.2286468036914234

[optimizer]
type = "AdamW"
lr = 0.000466492357927656
weight_decay = 3.5878177864117903e-06

[data]
seed = 0
path = ":data/delivery-eta"
cache = true
split = "sliding-window-0"
cat_policy = "ordinal"
num_policy = "identity"
