seed = 5
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "ResNet"
n_blocks = 3
d_block = 128
d_hidden_multiplier = 2
dropout1 = 0.499904690155194
dropout2 = 0.16933086372135409

[optimizer]
type = "AdamW"
lr = 5.787810772331574e-05
weight_decay = 1.048494987660001e-05

[data]
seed = 0
path = ":data/cooking-time"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "identity"
