seed = 6

[model]
n_estimators = 4000
stopping_rounds = 3999
device_type = "gpu"
verbose = 2
n_jobs = 4
feature_fraction = 0.5132113263550996
lambda_l2 = 0.0
learning_rate = 0.005666233524411183
num_leaves = 400
min_sum_hessian_in_leaf = 0.015712199619815827
bagging_fraction = 0.9209896391609289

[fit]

[data]
seed = 0
path = ":data/delivery-eta"
cache = true
split = "default"
cat_policy = "ordinal"
