seed = 4
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 512
dropout = 0.6781613841554205

[optimizer]
type = "AdamW"
lr = 1.953619219179762e-05
weight_decay = 2.7471120313639337e-06

[data]
seed = 0
path = ":data/homesite-insurance"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
