seed = 13
patience = 16
n_epochs = -1
batch_size = 256

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 2048
dropout = 0.7170383398943644

[optimizer]
type = "AdamW"
lr = 3.348573042989059e-05
weight_decay = 1.6244500153904918e-06

[data]
seed = 0
path = ":data/sberbank-housing"
cache = true
split = "sliding-window-0"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
