seed = 2

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.961655434234573
gamma = 0
lambda = 0.0
learning_rate = 0.010760238256281916
max_depth = 5
min_child_weight = 0.0011384831167083659
subsample = 0.8330446336168849

[fit]
verbose = true

[data]
seed = 0
path = ":data/homesite-insurance"
cache = true
split = "random-2"
cat_policy = "ordinal"
