seed = 13
patience = 16
n_epochs = -1
batch_size = 256

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 128
d_embedding = 32
frequency_init_scale = 0.04960883372272963
lite = false

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 1024
dropout = 0.40105797519313824

[optimizer]
type = "AdamW"
lr = 0.0004711762807053087
weight_decay = 2.788309620022656e-05

[data]
seed = 0
path = ":data/sberbank-housing"
cache = true
split = "sliding-window-2"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
