seed = 2

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.8645331722913336
gamma = 0.02124369255977036
lambda = 0.274288685142187
learning_rate = 0.0032916642791841868
max_depth = 14
min_child_weight = 43.726192187237636
subsample = 0.9568949094888759

[fit]
verbose = true

[data]
seed = 0
path = ":data/ecom-offers"
cache = true
split = "sliding-window-2"
