seed = 3
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 256
dropout = 0.4221356997828512

[optimizer]
type = "AdamW"
lr = 0.0007387615528298113
weight_decay = 0.00010001011931423624

[data]
seed = 0
path = ":data/ecom-offers"
cache = true
split = "random-0"
num_policy = "noisy-quantile"
