seed = 0
patience = 16
n_epochs = -1
batch_size = 1024

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 16
d_embedding = 32
frequency_init_scale = 0.03677617300176515
lite = false

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 512
dropout = 0.7255974803671966

[optimizer]
type = "AdamW"
lr = 0.0005218523909071557
weight_decay = 2.988804989639819e-05

[data]
seed = 0
path = ":data/homesite-insurance"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
