seed = 1
patience = 16
n_epochs = -1
batch_size = 1024

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 128
d_embedding = 32
frequency_init_scale = 0.013530320151288496
lite = false

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 2048
dropout = 0.5733983914739703

[optimizer]
type = "AdamW"
lr = 1.457180984613401e-05
weight_decay = 3.0119132997856615e-05

[data]
seed = 0
path = ":data/delivery-eta"
cache = true
split = "random-1"
cat_policy = "ordinal"
num_policy = "identity"
