seed = 4
patience = 16
n_epochs = -1
batch_size = 256

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 512
dropout = 0.09978712137053179

[optimizer]
type = "AdamW"
lr = 0.0003015698423739044
weight_decay = 0.0007379944743388058

[data]
seed = 0
path = ":data/sberbank-housing"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
