seed = 9
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 2048
dropout = 0.713115076980414

[optimizer]
type = "AdamW"
lr = 1.462549801636532e-05
weight_decay = 7.339032831824898e-06

[data]
seed = 0
path = ":data/maps-routing"
cache = true
split = "sliding-window-2"
cat_policy = "ordinal"
num_policy = "identity"
