seed = 14

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.5277859474867591
gamma = 0.0576368888245162
lambda = 0.0
learning_rate = 0.0053354022373130715
max_depth = 12
min_child_weight = 25.10323968193444
subsample = 0.953662805828835

[fit]
verbose = true

[data]
seed = 0
path = ":data/homesite-insurance"
cache = true
split = "sliding-window-0"
cat_policy = "ordinal"
