seed = 1
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 512
dropout = 0.557157243215502

[optimizer]
type = "AdamW"
lr = 3.452049388917989e-05
weight_decay = 5.226347792868542e-05

[data]
seed = 0
path = ":data/homesite-insurance"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
