seed = 9
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 256
dropout = 0.7318007426654952

[optimizer]
type = "AdamW"
lr = 0.0001284547021423807
weight_decay = 0.000240454203792106

[data]
seed = 0
path = ":data/homesite-insurance"
cache = true
split = "sliding-window-1"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
