seed = 13

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.6278170273138898
gamma = 0
lambda = 1.100177812848056
learning_rate = 0.027592083711965296
max_depth = 7
min_child_weight = 12.990619294311125
subsample = 0.6122107323401133

[fit]
verbose = true

[data]
seed = 0
path = ":data/ecom-offers"
cache = true
split = "random-1"
