seed = 6
patience = 16
n_epochs = -1
batch_size = 1024

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 128
d_embedding = 8
frequency_init_scale = 0.11685232576171223
lite = false

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 512
dropout = 0.443658259454362

[optimizer]
type = "AdamW"
lr = 1.5543868887998054e-05
weight_decay = 2.4520661345562125e-05

[data]
seed = 0
path = ":data/cooking-time"
cache = true
split = "random-2"
cat_policy = "ordinal"
num_policy = "identity"
