seed = 13
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "FTTransformerBackbone"
attention_n_heads = 8
ffn_d_hidden_multiplier = 2
ffn_activation = "ReLU"
residual_dropout = 0
n_blocks = 4
d_block = 256
attention_dropout = 0.1240695293311066
ffn_dropout = 0.2158134170107986

[model.num_embeddings]
type = "LinearEmbeddings"

[optimizer]
type = "AdamW"
lr = 3.68640326960085e-05
weight_decay = 3.665184382327534e-06

[data]
seed = 0
path = ":data/weather"
cache = true
split = "default"
num_policy = "noisy-quantile"
