seed = 2
patience = 16
n_epochs = -1
batch_size = 1024

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 2
d_embedding = 16
frequency_init_scale = 0.029524971465550075
lite = false

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 2048
dropout = 0.0

[optimizer]
type = "AdamW"
lr = 4.778523880962133e-05
weight_decay = 1.2731132051274298e-06

[data]
seed = 0
path = ":data/maps-routing"
cache = true
split = "random-1"
cat_policy = "ordinal"
num_policy = "identity"
