seed = 7
patience = 16
n_epochs = -1
batch_size = 1024

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 128
d_embedding = 4
frequency_init_scale = 0.1176304109101547
lite = false

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 2048
dropout = 0.22781777798803635

[optimizer]
type = "AdamW"
lr = 3.6824418346896863e-05
weight_decay = 1.2305610417293523e-06

[data]
seed = 0
path = ":data/homecredit-default"
cache = true
split = "random-0"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
