seed = 6
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 128
dropout = 0.4181472068230023

[optimizer]
type = "AdamW"
lr = 0.0002721305732485755
weight_decay = 9.116805938588478e-05

[data]
seed = 0
path = ":data/cooking-time"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "identity"
