seed = 9

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.5001851645889628
gamma = 73.72330530172022
lambda = 4.184827728518917
learning_rate = 0.0027494320961859594
max_depth = 7
min_child_weight = 0.13325385899267628
subsample = 0.7223169036765709

[fit]
verbose = true

[data]
seed = 0
path = ":data/ecom-offers"
cache = true
split = "sliding-window-0"
