seed = 7
patience = 16
n_epochs = -1
batch_size = 1024

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 128
d_embedding = 8
frequency_init_scale = 3.755540105800167
lite = false

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 256
dropout = 0.4078613264631853

[optimizer]
type = "AdamW"
lr = 1.0820468413128958e-05
weight_decay = 1.204280076624457e-06

[data]
seed = 0
path = ":data/ecom-offers"
cache = true
split = "default"
num_policy = "noisy-quantile"
