seed = 14

[model]
iterations = 4000
early_stopping_rounds = 3999
od_pval = 0.001
bagging_temperature = 0.4184425811874601
depth = 6
l2_leaf_reg = 4.316244695955154
leaf_estimation_iterations = 1
learning_rate = 0.02862422217834322
task_type = "CPU"
thread_count = 4

[fit]
logging_level = "Verbose"

[data]
seed = 0
path = ":data/sberbank-housing"
cache = true
split = "default"
cat_policy = "ordinal"
