seed = 11
patience = 16
n_epochs = -1
batch_size = 1024

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 128
d_embedding = 2
frequency_init_scale = 0.02688449737122624
lite = false

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 2048
dropout = 0.0

[optimizer]
type = "AdamW"
lr = 1.1851321646959686e-05
weight_decay = 2.864355294203472e-06

[data]
seed = 0
path = ":data/maps-routing"
cache = true
split = "sliding-window-2"
cat_policy = "ordinal"
num_policy = "identity"
