seed = 11

[model]
n_estimators = 4000
stopping_rounds = 3999
device_type = "gpu"
verbose = 2
n_jobs = 4
feature_fraction = 0.5003098774590061
lambda_l2 = 0.0
learning_rate = 0.005692025617334992
num_leaves = 221
min_sum_hessian_in_leaf = 49.45973705291668
bagging_fraction = 0.8906888012501057

[fit]

[data]
seed = 0
path = ":data/maps-routing"
cache = true
split = "default"
cat_policy = "ordinal"
