seed = 1
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "DCNv2"
d_cat_embedding = 32
d_deep = 128
n_cross_layers = 1
n_deep_layers = 3
dropout_p = 0.2384336563827928
nonlin_cross = false

[optimizer]
type = "AdamW"
lr = 0.0002835770203645389
weight_decay = 4.884914775176373e-05

[data]
seed = 0
path = ":data/cooking-time"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "identity"
