seed = 14

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.6639572967418735
gamma = 0
lambda = 0.0
learning_rate = 0.005253423341867364
max_depth = 8
min_child_weight = 0.11026288357613705
subsample = 0.6076897273762274

[fit]
verbose = true

[data]
seed = 0
path = ":data/cooking-time"
cache = true
split = "sliding-window-2"
cat_policy = "ordinal"
