seed = 2
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 128
dropout = 0.5301591503199592

[optimizer]
type = "AdamW"
lr = 0.00014931312505075256
weight_decay = 2.2441356474271885e-05

[data]
seed = 0
path = ":data/homesite-insurance"
cache = true
split = "sliding-window-0"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
