seed = 6

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.5787869502107212
gamma = 0
lambda = 2.29496527579423
learning_rate = 0.031143436952080734
max_depth = 10
min_child_weight = 0.03490683205462036
subsample = 0.9996971812594041

[fit]
verbose = true

[data]
seed = 0
path = ":data/weather"
cache = true
split = "random-2"
