seed = 10
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "FTTransformerBackbone"
attention_n_heads = 8
ffn_d_hidden_multiplier = 2
ffn_activation = "ReLU"
residual_dropout = 0
n_blocks = 3
d_block = 128
attention_dropout = 0.11777636977924688
ffn_dropout = 0.09585861179736897

[model.num_embeddings]
type = "LinearEmbeddings"

[optimizer]
type = "AdamW"
lr = 3.405284535814795e-05
weight_decay = 0.00013289855371901834

[data]
seed = 0
path = ":data/homesite-insurance"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
