seed = 4
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 128
dropout = 0.17161120282593711

[optimizer]
type = "AdamW"
lr = 0.00027784575690737194
weight_decay = 4.869802083550242e-05

[data]
seed = 0
path = ":data/delivery-eta"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "identity"
