seed = 7
patience = 16
n_epochs = -1
batch_size = 1024

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 128
d_embedding = 32
frequency_init_scale = 0.028942020087653193
lite = false

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 1024
dropout = 0.3411795678749082

[optimizer]
type = "AdamW"
lr = 0.00010539430818043947
weight_decay = 0.00019952047888764442

[data]
seed = 0
path = ":data/cooking-time"
cache = true
split = "sliding-window-1"
cat_policy = "ordinal"
num_policy = "identity"
