seed = 4
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 128
dropout = 0.5403363519102373

[optimizer]
type = "AdamW"
lr = 9.99954604899212e-05
weight_decay = 3.928327003555748e-05

[data]
seed = 0
path = ":data/homesite-insurance"
cache = true
split = "random-0"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
