seed = 9

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.8360080965494098
gamma = 0.13200903451879464
lambda = 0.0
learning_rate = 0.00879957558851596
max_depth = 10
min_child_weight = 4.290688752611936
subsample = 0.9038593566717298

[fit]
verbose = true

[data]
seed = 0
path = ":data/homesite-insurance"
cache = true
split = "random-1"
cat_policy = "ordinal"
