seed = 3
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 512
dropout = 0.7011344209732379

[optimizer]
type = "AdamW"
lr = 0.000960699207299998
weight_decay = 9.322626101265907e-05

[data]
seed = 0
path = ":data/ecom-offers"
cache = true
split = "sliding-window-0"
num_policy = "noisy-quantile"
