seed = 4
patience = 16
n_epochs = -1
causal = false
batch_size = 1024
context_size = 96

[model]
d_main = 256
context_dropout = 0.5808639250372823
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.005510493583059741
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 0.0009674329191198645
weight_decay = 0.00015539898152564795

[data]
seed = 0
path = ":data/ecom-offers"
cache = true
split = "random-2"
num_policy = "noisy-quantile"
