seed = 8
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "ResNet"
n_blocks = 4
d_block = 512
d_hidden_multiplier = 2
dropout1 = 0.49935382794777694
dropout2 = 0.025914358653375075

[optimizer]
type = "AdamW"
lr = 0.0007498144621815564
weight_decay = 4.6686183895680727e-05

[data]
seed = 0
path = ":data/weather"
cache = true
split = "default"
num_policy = "noisy-quantile"
