seed = 4

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.8897831195908247
gamma = 0
lambda = 9.023268389452678
learning_rate = 0.019373279583235595
max_depth = 3
min_child_weight = 0.0003233132448505383
subsample = 0.88886610640258

[fit]
verbose = true

[data]
seed = 0
path = ":data/sberbank-housing"
cache = true
split = "default"
cat_policy = "ordinal"
