seed = 6

[model]
iterations = 4000
early_stopping_rounds = 3999
od_pval = 0.001
bagging_temperature = 0.37679844600139817
depth = 8
l2_leaf_reg = 4.343375626590167
leaf_estimation_iterations = 7
learning_rate = 0.01777689093587204
task_type = "CPU"
thread_count = 4

[fit]
logging_level = "Verbose"

[data]
seed = 0
path = ":data/cooking-time"
cache = true
split = "default"
cat_policy = "ordinal"
