seed = 11
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 256
dropout = 0.606756488729125

[optimizer]
type = "AdamW"
lr = 0.00025213590700975166
weight_decay = 2.393512812564068e-06

[data]
seed = 0
path = ":data/cooking-time"
cache = true
split = "random-1"
cat_policy = "ordinal"
num_policy = "identity"
