seed = 0

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.7146217642017421
gamma = 0
lambda = 0.0
learning_rate = 0.004497275937023875
max_depth = 10
min_child_weight = 0.39424691104297827
subsample = 0.6924263249803857

[fit]
verbose = true

[data]
seed = 0
path = ":data/cooking-time"
cache = true
split = "random-1"
cat_policy = "ordinal"
