seed = 6
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "SNN"
n_blocks = 14
d_block = 2048
dropout = 0.0

[optimizer]
type = "AdamW"
lr = 0.0003639639356786391
weight_decay = 2.263722969739549e-06

[data]
seed = 0
path = ":data/maps-routing"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "identity"
