seed = 14
patience = 16
n_epochs = -1
batch_size = 1024

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 64
d_embedding = 32
frequency_init_scale = 0.1016784653607343
lite = false

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 1024
dropout = 0.0

[optimizer]
type = "AdamW"
lr = 1.5567453625654786e-05
weight_decay = 9.634895963946702e-05

[data]
seed = 0
path = ":data/delivery-eta"
cache = true
split = "sliding-window-1"
cat_policy = "ordinal"
num_policy = "identity"
