seed = 11

[model]
n_estimators = 4000
stopping_rounds = 3999
device_type = "gpu"
verbose = 2
n_jobs = 4
feature_fraction = 0.7033468703367834
lambda_l2 = 0.0
learning_rate = 0.0053407036185410565
num_leaves = 227
min_sum_hessian_in_leaf = 99.24499954259626
bagging_fraction = 0.564448499597343

[fit]

[data]
seed = 0
path = ":data/homecredit-default"
cache = true
split = "default"
cat_policy = "ordinal"
