seed = 12
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 256
dropout = 0.598946118283001

[optimizer]
type = "AdamW"
lr = 1.496746335438327e-05
weight_decay = 3.931515939300571e-05

[data]
seed = 0
path = ":data/homecredit-default"
cache = true
split = "sliding-window-1"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
