seed = 7
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "SNN"
n_blocks = 2
d_block = 512
dropout = 0.0

[optimizer]
type = "AdamW"
lr = 0.0006142776326402168
weight_decay = 1.5953651460249276e-05

[data]
seed = 0
path = ":data/weather"
cache = true
split = "default"
num_policy = "noisy-quantile"
