seed = 11

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.5325715163837621
gamma = 0.005752834117202057
lambda = 0.0
learning_rate = 0.007775639612783999
max_depth = 8
min_child_weight = 38.400700293517254
subsample = 0.7502467208270847

[fit]
verbose = true

[data]
seed = 0
path = ":data/delivery-eta"
cache = true
split = "random-2"
cat_policy = "ordinal"
