seed = 6
patience = 16
n_epochs = -1
batch_size = 1024

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 2
d_embedding = 4
frequency_init_scale = 0.05473772722053145
lite = false

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 2048
dropout = 0.7165179599623918

[optimizer]
type = "AdamW"
lr = 7.985983638621394e-05
weight_decay = 0.00019557924806240184

[data]
seed = 0
path = ":data/weather"
cache = true
split = "random-0"
num_policy = "noisy-quantile"
