seed = 12
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 2048
dropout = 0.7268998820366207

[optimizer]
type = "AdamW"
lr = 3.2101907857511827e-05
weight_decay = 0.0002889421597953228

[data]
seed = 0
path = ":data/maps-routing"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "identity"
