seed = 1
patience = 16
n_epochs = -1
batch_size = 1024

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 64
d_embedding = 32
frequency_init_scale = 0.01083393498996152
lite = false

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 1024
dropout = 0.42988949357542416

[optimizer]
type = "AdamW"
lr = 0.0003284958599272857
weight_decay = 3.403131901642142e-06

[data]
seed = 0
path = ":data/weather"
cache = true
split = "default"
num_policy = "noisy-quantile"
