seed = 0
patience = 16
n_epochs = -1
batch_size = 1024

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 128
d_embedding = 8
frequency_init_scale = 0.05060160687110336
lite = false

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 1024
dropout = 0.0

[optimizer]
type = "AdamW"
lr = 2.9236105234891787e-05
weight_decay = 1.2145118674711516e-06

[data]
seed = 0
path = ":data/homecredit-default"
cache = true
split = "sliding-window-0"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
