seed = 7
patience = 16
n_epochs = -1
causal = false
batch_size = 1024
context_size = 96

[model]
d_main = 256
context_dropout = 0.4999934843476623
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.33618734849136017
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 6.574495615908198e-05
weight_decay = 4.2138128842219e-05

[data]
seed = 0
path = ":data/cooking-time"
cache = true
split = "random-0"
cat_policy = "ordinal"
num_policy = "identity"
