seed = 0
patience = 16
n_epochs = -1
batch_size = 1024

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 16
d_embedding = 32
frequency_init_scale = 0.019959602304121943
lite = false

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 512
dropout = 0.046525257629940364

[optimizer]
type = "AdamW"
lr = 0.0001483314289742837
weight_decay = 1.541340669706212e-05

[data]
seed = 0
path = ":data/homecredit-default"
cache = true
split = "random-2"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
