seed = 9
patience = 16
n_epochs = -1
causal = false
batch_size = 256
context_size = 96

[model]
d_main = 256
context_dropout = 0.43727872811967483
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.16951767347238456
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 2.5648335028019744e-05
weight_decay = 1.9717156750554534e-05

[data]
seed = 0
path = ":data/sberbank-housing"
cache = true
split = "random-2"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
