seed = 11
patience = 16
n_epochs = -1
batch_size = 1024

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 32
d_embedding = 16
frequency_init_scale = 0.018594781087425367
lite = false

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 2048
dropout = 0.0

[optimizer]
type = "AdamW"
lr = 4.42659942564846e-05
weight_decay = 8.697574246043832e-06

[data]
seed = 0
path = ":data/maps-routing"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "identity"
