seed = 10
patience = 16
n_epochs = -1
batch_size = 1024

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 64
d_embedding = 32
frequency_init_scale = 0.011347731864912992
lite = false

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 2048
dropout = 0.6675006947057336

[optimizer]
type = "AdamW"
lr = 0.00029463400145599944
weight_decay = 1.0400214433453297e-05

[data]
seed = 0
path = ":data/weather"
cache = true
split = "sliding-window-1"
num_policy = "noisy-quantile"
