seed = 0
patience = 16
n_epochs = -1
batch_size = 1024

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 2
d_embedding = 8
frequency_init_scale = 0.025128271463019398
lite = false

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 2048
dropout = 0.48197428856163593

[optimizer]
type = "AdamW"
lr = 0.00013015362351266566
weight_decay = 3.2967678165905582e-06

[data]
seed = 0
path = ":data/homecredit-default"
cache = true
split = "sliding-window-1"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
