seed = 1
patience = 16
n_epochs = -1
batch_size = 1024

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 32
d_embedding = 32
frequency_init_scale = 0.04264774070600289
lite = false

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 1024
dropout = 0.0

[optimizer]
type = "AdamW"
lr = 3.7445301843490535e-05
weight_decay = 0.00015534971018208747

[data]
seed = 0
path = ":data/delivery-eta"
cache = true
split = "sliding-window-2"
cat_policy = "ordinal"
num_policy = "identity"
