seed = 13
patience = 16
n_epochs = -1
batch_size = 256

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 2048
dropout = 0.4713329349954013

[optimizer]
type = "AdamW"
lr = 0.0005411293150753388
weight_decay = 9.712335020137967e-05

[data]
seed = 0
path = ":data/sberbank-housing"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
