seed = 5
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "ResNet"
n_blocks = 4
d_block = 256
d_hidden_multiplier = 2
dropout1 = 0.479523186764242
dropout2 = 0.10443144022171472

[optimizer]
type = "AdamW"
lr = 0.0004778252074670133
weight_decay = 1.7140852141321134e-06

[data]
seed = 0
path = ":data/homesite-insurance"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
