seed = 10
patience = 16
n_epochs = -1
batch_size = 256

[model.backbone]
type = "SNN"
n_blocks = 6
d_block = 128
dropout = 0.047753203930902724

[optimizer]
type = "AdamW"
lr = 6.189392414052224e-05
weight_decay = 0.00041191714401826827

[data]
seed = 0
path = ":data/sberbank-housing"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
