seed = 5
patience = 16
n_epochs = -1
causal = false
batch_size = 1024
context_size = 96

[model]
d_main = 256
context_dropout = 0.4957544220454839
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.08346472820459781
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 0.00012149877568065094
weight_decay = 1.1893538705199909e-05

[data]
seed = 0
path = ":data/weather"
cache = true
split = "sliding-window-1"
num_policy = "noisy-quantile"
