seed = 0

[data]
seed = 0
cache = true
path = ":data/sberbank-housing"
cat_policy = "ordinal"
split = "default"

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.8192220466765512
gamma = 0.0015476918478467441
lambda = 6.846129466325879
learning_rate = 0.014086527530531896
max_depth = 6
min_child_weight = 0.876490673110794
subsample = 0.8447209720231161

[fit]

verbose = true
