seed = 9
patience = 16
n_epochs = -1
batch_size = 256

[model.backbone]
type = "DCNv2"
d_cat_embedding = 8
d_deep = 128
n_cross_layers = 1
n_deep_layers = 3
dropout_p = 0.3309184602097069
nonlin_cross = false

[optimizer]
type = "AdamW"
lr = 0.0005201755030701926
weight_decay = 3.813383539931073e-05

[data]
seed = 0
path = ":data/sberbank-housing"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
