seed = 4
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 128
dropout = 0.5114757599552668

[optimizer]
type = "AdamW"
lr = 0.0003981705160126184
weight_decay = 2.177108939103459e-05

[data]
seed = 0
path = ":data/cooking-time"
cache = true
split = "sliding-window-2"
cat_policy = "ordinal"
num_policy = "identity"
