seed = 14

[model]
n_estimators = 4000
stopping_rounds = 3999
device_type = "gpu"
verbose = 2
n_jobs = 4
feature_fraction = 0.5495899012681111
lambda_l2 = 0.0
learning_rate = 0.0031456595198807854
num_leaves = 534
min_sum_hessian_in_leaf = 70.77368432902227
bagging_fraction = 0.5899037088943635

[fit]

[data]
seed = 0
path = ":data/cooking-time"
cache = true
split = "default"
cat_policy = "ordinal"
