seed = 13

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.8598565266166941
gamma = 0
lambda = 4.5161830250565815
learning_rate = 0.0048963459967354
max_depth = 8
min_child_weight = 1.6009270456840954
subsample = 0.8266382791316769

[fit]
verbose = true

[data]
seed = 0
path = ":data/cooking-time"
cache = true
split = "sliding-window-1"
cat_policy = "ordinal"
