seed = 5
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "FTTransformerBackbone"
attention_n_heads = 8
ffn_d_hidden_multiplier = 2
ffn_activation = "ReLU"
residual_dropout = 0
n_blocks = 2
d_block = 256
attention_dropout = 0.09277530392520592
ffn_dropout = 0.38807357804004383

[model.num_embeddings]
type = "LinearEmbeddings"

[optimizer]
type = "AdamW"
lr = 0.0007275778408047029
weight_decay = 2.7915701474483565e-06

[data]
seed = 0
path = ":data/ecom-offers"
cache = true
split = "default"
num_policy = "noisy-quantile"
