seed = 9

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.6158148827572494
gamma = 0.016118012384737493
lambda = 4.863552776604434
learning_rate = 0.005758099416763697
max_depth = 9
min_child_weight = 63.35205026944564
subsample = 0.6629948505009582

[fit]
verbose = true

[data]
seed = 0
path = ":data/maps-routing"
cache = true
split = "random-2"
cat_policy = "ordinal"
