seed = 10
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 2048
dropout = 0.43988748351419144

[optimizer]
type = "AdamW"
lr = 1.3610998513502132e-05
weight_decay = 8.124167215126981e-05

[data]
seed = 0
path = ":data/cooking-time"
cache = true
split = "random-0"
cat_policy = "ordinal"
num_policy = "identity"
