seed = 9
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "ResNet"
n_blocks = 4
d_block = 512
d_hidden_multiplier = 2
dropout1 = 0.48248788784832763
dropout2 = 0.0

[optimizer]
type = "AdamW"
lr = 0.0008943367160587468
weight_decay = 1.1273256725609113e-05

[data]
seed = 0
path = ":data/delivery-eta"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "identity"
