seed = 13
patience = 16
n_epochs = -1
batch_size = 1024

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 64
d_embedding = 8
frequency_init_scale = 0.10817096796833704
lite = false

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 256
dropout = 0.7047458620846271

[optimizer]
type = "AdamW"
lr = 0.0005390286425426002
weight_decay = 1.1816897514427746e-05

[data]
seed = 0
path = ":data/homesite-insurance"
cache = true
split = "sliding-window-2"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
