seed = 4

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.6091405688884225
gamma = 4.029956238489894
lambda = 0.0
learning_rate = 0.9730668661310043
max_depth = 3
min_child_weight = 0.054469889182187245
subsample = 0.8605582556408533

[fit]
verbose = true

[data]
seed = 0
path = ":data/ecom-offers"
cache = true
split = "default"
