seed = 3

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.9568607918605903
gamma = 98.39523852123828
lambda = 4.375759983103515
learning_rate = 0.01605058034354761
max_depth = 9
min_child_weight = 9.53566661909492
subsample = 0.5311998831105121

[fit]
verbose = true

[data]
seed = 0
path = ":data/ecom-offers"
cache = true
split = "sliding-window-1"
