seed = 6
patience = 16
n_epochs = -1
causal = true
batch_size = 1024
context_size = 96

[model]
d_main = 256
context_dropout = 0.48123780959359685
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.16669350390602733
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 5.637583135200244e-05
weight_decay = 4.427419256153457e-05

[data]
seed = 0
path = ":data/delivery-eta"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "identity"
