seed = 0
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 2048
dropout = 0.40144178373552514

[optimizer]
type = "AdamW"
lr = 0.0007220610653633619
weight_decay = 7.104400217452954e-05

[data]
seed = 0
path = ":data/weather"
cache = true
split = "random-1"
num_policy = "noisy-quantile"
