seed = 14

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.805639418210311
gamma = 0.1855078257201285
lambda = 6.33604642740767
learning_rate = 0.003096269838895894
max_depth = 6
min_child_weight = 1.5195046500967784
subsample = 0.9150265212390128

[fit]
verbose = true

[data]
seed = 0
path = ":data/sberbank-housing"
cache = true
split = "sliding-window-1"
cat_policy = "ordinal"
