seed = 6
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 512
dropout = 0.6349265734875958

[optimizer]
type = "AdamW"
lr = 0.00014931276503608008
weight_decay = 0.0009469121305987542

[data]
seed = 0
path = ":data/ecom-offers"
cache = true
split = "sliding-window-2"
num_policy = "noisy-quantile"
