seed = 4
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "DCNv2"
d_cat_embedding = 32
d_deep = 1024
n_cross_layers = 4
n_deep_layers = 2
dropout_p = 0.26970456768883005
nonlin_cross = false

[optimizer]
type = "AdamW"
lr = 0.00019699649094745986
weight_decay = 2.9067444549824783e-06

[data]
seed = 0
path = ":data/homesite-insurance"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
