seed = 4
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "DCNv2"
d_cat_embedding = 32
d_deep = 512
n_cross_layers = 1
n_deep_layers = 4
dropout_p = 0.0
nonlin_cross = false

[optimizer]
type = "AdamW"
lr = 0.0005259770126881451
weight_decay = 6.05318147334114e-06

[data]
seed = 0
path = ":data/homecredit-default"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
