seed = 8
patience = 16
n_epochs = -1
batch_size = 1024

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 64
d_embedding = 2
frequency_init_scale = 0.02257445422492953
lite = false

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 512
dropout = 0.5159691754070743

[optimizer]
type = "AdamW"
lr = 9.624369860413216e-05
weight_decay = 3.8125971444259084e-06

[data]
seed = 0
path = ":data/cooking-time"
cache = true
split = "random-1"
cat_policy = "ordinal"
num_policy = "identity"
