seed = 8
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "ResNet"
n_blocks = 3
d_block = 256
d_hidden_multiplier = 2
dropout1 = 0.49970175252769544
dropout2 = 0.4258114950057277

[optimizer]
type = "AdamW"
lr = 4.2981702003444884e-05
weight_decay = 2.3209584562768377e-05

[data]
seed = 0
path = ":data/maps-routing"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "identity"
