seed = 7
patience = 16
n_epochs = -1
batch_size = 1024

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 128
d_embedding = 16
frequency_init_scale = 0.02651000576591762
lite = false

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 1024
dropout = 0.6697622943531011

[optimizer]
type = "AdamW"
lr = 1.3248831803300388e-05
weight_decay = 3.1286975976941828e-06

[data]
seed = 0
path = ":data/delivery-eta"
cache = true
split = "random-2"
cat_policy = "ordinal"
num_policy = "identity"
