seed = 8
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 256
dropout = 0.15346176943244708

[optimizer]
type = "AdamW"
lr = 0.0006539193897818584
weight_decay = 0.00033349264602086637

[data]
seed = 0
path = ":data/weather"
cache = true
split = "sliding-window-0"
num_policy = "noisy-quantile"
