seed = 9

[model]
n_estimators = 4000
stopping_rounds = 3999
device_type = "gpu"
verbose = 2
n_jobs = 4
feature_fraction = 0.5468975648771445
lambda_l2 = 3.0104994315200937
learning_rate = 0.005095450482639915
num_leaves = 16
min_sum_hessian_in_leaf = 41.62512242363803
bagging_fraction = 0.8361345074976962

[fit]

[data]
seed = 0
path = ":data/sberbank-housing"
cache = true
split = "default"
cat_policy = "ordinal"
