seed = 10
patience = 16
n_epochs = -1
causal = false
batch_size = 1024
context_size = 96

[model]
d_main = 256
context_dropout = 0.5917676430399155
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.11752980797608112
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 3.442234419404676e-05
weight_decay = 0.0003989157908960743

[data]
seed = 0
path = ":data/weather"
cache = true
split = "sliding-window-2"
num_policy = "noisy-quantile"
