seed = 0
patience = 16
n_epochs = -1
causal = false
batch_size = 1024
context_size = 96

[model]
d_main = 256
context_dropout = 0.5943334527352481
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.5258905569257921
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 6.530698170025576e-05
weight_decay = 0.0003870610283439195

[data]
seed = 0
path = ":data/homesite-insurance"
cache = true
split = "random-0"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
