seed = 0
function = "bin.nn_baselines.main"
n_trials = 100

[space]
seed = 0
patience = 16
n_epochs = -1
batch_size = 1024

[space.model.backbone]
type = "MLP"
n_blocks = [
    "_tune_",
    "int",
    1,
    4,
]
d_block = [
    "_tune_",
    "int-power-of-two",
    7,
    11,
]
dropout = [
    "_tune_",
    "?uniform",
    0.0,
    0.0,
    0.75,
]

[space.optimizer]
type = "AdamW"
lr = [
    "_tune_",
    "loguniform",
    1e-05,
    0.001,
]
weight_decay = [
    "_tune_",
    "loguniform",
    1e-06,
    0.001,
]

[space.data]
seed = 0
path = ":data/cooking-time"
cache = true
split = "random-0"
cat_policy = "ordinal"
num_policy = "identity"
