seed = 8

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.5212830679806896
gamma = 0
lambda = 0.9891450016156724
learning_rate = 0.017249556042922297
max_depth = 9
min_child_weight = 23.422011119182482
subsample = 0.9889884359599425

[fit]
verbose = true

[data]
seed = 0
path = ":data/weather"
cache = true
split = "sliding-window-0"
