seed = 6

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.5617295820015251
gamma = 0
lambda = 0.0
learning_rate = 0.010361775571983277
max_depth = 10
min_child_weight = 0.012683888958062956
subsample = 0.9683129815933444

[fit]
verbose = true

[data]
seed = 0
path = ":data/weather"
cache = true
split = "sliding-window-1"
