seed = 13
patience = 16
n_epochs = -1
batch_size = 256

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 2048
dropout = 0.04689414631293065

[optimizer]
type = "AdamW"
lr = 0.000789766959240223
weight_decay = 0.00039298038595349634

[data]
seed = 0
path = ":data/sberbank-housing"
cache = true
split = "sliding-window-1"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
