seed = 6
patience = 16
n_epochs = -1
batch_size = 1024

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 4
d_embedding = 8
frequency_init_scale = 0.029303202790457675
lite = false

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 256
dropout = 0.0

[optimizer]
type = "AdamW"
lr = 0.00012792563088586038
weight_decay = 0.0006404463813102048

[data]
seed = 0
path = ":data/ecom-offers"
cache = true
split = "random-1"
num_policy = "noisy-quantile"
