seed = 1
patience = 16
n_epochs = -1
batch_size = 1024

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 64
d_embedding = 4
frequency_init_scale = 0.1045854323097666
lite = false

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 2048
dropout = 0.7495512507716723

[optimizer]
type = "AdamW"
lr = 4.929555219743888e-05
weight_decay = 4.29995456040889e-05

[data]
seed = 0
path = ":data/cooking-time"
cache = true
split = "sliding-window-0"
cat_policy = "ordinal"
num_policy = "identity"
