seed = 0
patience = 16
n_epochs = -1
causal = false
batch_size = 1024
context_size = 96

[model]
d_main = 128
context_dropout = 0.5137239705303014
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.22686132030664866
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 6.361743593609747e-05
weight_decay = 4.591229031386377e-05

[data]
seed = 0
path = ":data/maps-routing"
cache = true
split = "random-2"
cat_policy = "ordinal"
num_policy = "identity"
