seed = 9
patience = 16
n_epochs = -1
causal = false
batch_size = 1024
context_size = 96

[model]
d_main = 256
context_dropout = 0.5843625536265948
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.03657762674604659
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 2.8260946187629726e-05
weight_decay = 7.986969106723651e-06

[data]
seed = 0
path = ":data/maps-routing"
cache = true
split = "sliding-window-2"
cat_policy = "ordinal"
num_policy = "identity"
