seed = 4
patience = 16
n_epochs = -1
batch_size = 1024

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 128
d_embedding = 8
frequency_init_scale = 0.18631673362724271
lite = false

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 256
dropout = 0.0

[optimizer]
type = "AdamW"
lr = 0.0007011382281201303
weight_decay = 1.093924006413596e-06

[data]
seed = 0
path = ":data/homesite-insurance"
cache = true
split = "sliding-window-0"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
