seed = 3
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 2048
dropout = 0.7142315525989626

[optimizer]
type = "AdamW"
lr = 1.0296467691685675e-05
weight_decay = 2.236300031313244e-06

[data]
seed = 0
path = ":data/maps-routing"
cache = true
split = "sliding-window-1"
cat_policy = "ordinal"
num_policy = "identity"
