seed = 5
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "SNN"
n_blocks = 1
d_block = 128
dropout = 0.0

[optimizer]
type = "AdamW"
lr = 0.00018082317139927153
weight_decay = 0.000748972261511723

[data]
seed = 0
path = ":data/cooking-time"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "identity"
