seed = 2
patience = 16
n_epochs = -1
batch_size = 256

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 512
dropout = 0.7495413685598237

[optimizer]
type = "AdamW"
lr = 1.840590058614594e-05
weight_decay = 0.0009906123486085798

[data]
seed = 0
path = ":data/sberbank-housing"
cache = true
split = "random-0"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
