seed = 11
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "SNN"
n_blocks = 7
d_block = 2048
dropout = 0.08704807618578533

[optimizer]
type = "AdamW"
lr = 0.00022844730439508827
weight_decay = 3.728303462885177e-06

[data]
seed = 0
path = ":data/homesite-insurance"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
