seed = 8

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.7746579623939366
gamma = 0
lambda = 0.0
learning_rate = 0.009330073450813464
max_depth = 7
min_child_weight = 3.2412668933024276
subsample = 0.9125241080038524

[fit]
verbose = true

[data]
seed = 0
path = ":data/homesite-insurance"
cache = true
split = "sliding-window-2"
cat_policy = "ordinal"
