seed = 5

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.5833104460433639
gamma = 0
lambda = 8.839319828723475
learning_rate = 0.025668612573256283
max_depth = 10
min_child_weight = 0.0021585904391044635
subsample = 0.9339099414979081

[fit]
verbose = true

[data]
seed = 0
path = ":data/weather"
cache = true
split = "random-0"
