seed = 12

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.7941564923594493
gamma = 0
lambda = 3.522950136464801
learning_rate = 0.004771890153694689
max_depth = 10
min_child_weight = 53.92756364503285
subsample = 0.7520126713923945

[fit]
verbose = true

[data]
seed = 0
path = ":data/homecredit-default"
cache = true
split = "random-1"
cat_policy = "ordinal"
