seed = 1
patience = 16
n_epochs = -1
causal = false
batch_size = 1024
context_size = 96

[model]
d_main = 256
context_dropout = 0.15484827672292745
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.5721411873033594
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 2.8260946187629726e-05
weight_decay = 0.0001834301563553207

[data]
seed = 0
path = ":data/weather"
cache = true
split = "random-1"
num_policy = "noisy-quantile"
