seed = 14

[model]
n_estimators = 4000
stopping_rounds = 3999
device_type = "gpu"
verbose = 2
n_jobs = 4
feature_fraction = 0.5128040385220566
lambda_l2 = 0.0
learning_rate = 0.006737269065992983
num_leaves = 107
min_sum_hessian_in_leaf = 1.2293843399508766
bagging_fraction = 0.5956394990208279

[fit]

[data]
seed = 0
path = ":data/homesite-insurance"
cache = true
split = "default"
cat_policy = "ordinal"
