seed = 9

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.7279249136036231
gamma = 0.011692813006144814
lambda = 2.2197233835828194
learning_rate = 0.004752478253556552
max_depth = 8
min_child_weight = 0.0001970182712539802
subsample = 0.8222808036922105

[fit]
verbose = true

[data]
seed = 0
path = ":data/cooking-time"
cache = true
split = "sliding-window-0"
cat_policy = "ordinal"
