seed = 10
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 128
dropout = 0.5209933073113894

[optimizer]
type = "AdamW"
lr = 0.0002907783440826815
weight_decay = 2.423546318204885e-06

[data]
seed = 0
path = ":data/homesite-insurance"
cache = true
split = "sliding-window-2"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
