seed = 3
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "DCNv2"
d_cat_embedding = 16
d_deep = 1024
n_cross_layers = 1
n_deep_layers = 2
dropout_p = 0.4066009361884444
nonlin_cross = false

[optimizer]
type = "AdamW"
lr = 0.00031195462499282353
weight_decay = 6.489615270973036e-05

[data]
seed = 0
path = ":data/maps-routing"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "identity"
