seed = 10

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.5002688020867827
gamma = 0
lambda = 6.298889001849771
learning_rate = 0.00851876025128321
max_depth = 8
min_child_weight = 3.1031214878539957
subsample = 0.7321081112037975

[fit]
verbose = true

[data]
seed = 0
path = ":data/delivery-eta"
cache = true
split = "sliding-window-2"
cat_policy = "ordinal"
