seed = 10
patience = 16
n_epochs = -1
batch_size = 256

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 128
dropout = 0.26106129088327684

[optimizer]
type = "AdamW"
lr = 1.049109741437505e-05
weight_decay = 1.036053354354035e-06

[data]
seed = 0
path = ":data/sberbank-housing"
cache = true
split = "sliding-window-2"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
