seed = 14
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 2048
dropout = 0.7199360744504973

[optimizer]
type = "AdamW"
lr = 1.4073931651170699e-05
weight_decay = 1.3370937458840148e-06

[data]
seed = 0
path = ":data/maps-routing"
cache = true
split = "random-0"
cat_policy = "ordinal"
num_policy = "identity"
