seed = 5

[model]
iterations = 4000
early_stopping_rounds = 3999
od_pval = 0.001
bagging_temperature = 0.014612750477688369
depth = 10
l2_leaf_reg = 5.095847336678159
leaf_estimation_iterations = 5
learning_rate = 0.014445693768153014
task_type = "CPU"
thread_count = 4

[fit]
logging_level = "Verbose"

[data]
seed = 0
path = ":data/homesite-insurance"
cache = true
split = "default"
cat_policy = "ordinal"
