seed = 2
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "DCNv2"
d_cat_embedding = 32
d_deep = 512
n_cross_layers = 2
n_deep_layers = 1
dropout_p = 0.45114442113381065
nonlin_cross = false

[optimizer]
type = "AdamW"
lr = 0.0008414678193467866
weight_decay = 1.9183697706302674e-05

[data]
seed = 0
path = ":data/delivery-eta"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "identity"
