seed = 11
patience = 16
n_epochs = -1
causal = false
batch_size = 1024
context_size = 96

[model]
d_main = 128
context_dropout = 0.591541008895872
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.0
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 0.0009511499211207801
weight_decay = 1.1050297014097916e-06

[data]
seed = 0
path = ":data/delivery-eta"
cache = true
split = "sliding-window-2"
cat_policy = "ordinal"
num_policy = "identity"
