seed = 10

[model]
iterations = 4000
early_stopping_rounds = 3999
od_pval = 0.001
bagging_temperature = 0.2503508089914244
depth = 11
l2_leaf_reg = 1.942043998141966
leaf_estimation_iterations = 1
learning_rate = 0.8021643909740948
task_type = "CPU"
thread_count = 4

[fit]
logging_level = "Verbose"

[data]
seed = 0
path = ":data/ecom-offers"
cache = true
split = "default"
