seed = 5
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 128
dropout = 0.2542324033575713

[optimizer]
type = "AdamW"
lr = 0.00047405238386019
weight_decay = 0.00019648398751718988

[data]
seed = 0
path = ":data/delivery-eta"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "identity"
