seed = 7
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 1024
dropout = 0.15541565900835594

[optimizer]
type = "AdamW"
lr = 9.932409069220459e-05
weight_decay = 1.0809276725747414e-06

[data]
seed = 0
path = ":data/weather"
cache = true
split = "random-0"
num_policy = "noisy-quantile"
