seed = 2
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "FTTransformerBackbone"
attention_n_heads = 8
ffn_d_hidden_multiplier = 2
ffn_activation = "ReLU"
residual_dropout = 0
n_blocks = 2
d_block = 256
attention_dropout = 0.22807516610827427
ffn_dropout = 0.28421697443432425

[model.num_embeddings]
type = "LinearEmbeddings"

[optimizer]
type = "AdamW"
lr = 1.090384328196852e-05
weight_decay = 7.126995609048586e-05

[data]
seed = 0
path = ":data/homecredit-default"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
