seed = 7
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "ResNet"
n_blocks = 2
d_block = 2048
d_hidden_multiplier = 2
dropout1 = 0.481491771494418
dropout2 = 0.44638587855279754

[optimizer]
type = "AdamW"
lr = 0.0007043130052476768
weight_decay = 2.5148010078935406e-06

[data]
seed = 0
path = ":data/ecom-offers"
cache = true
split = "default"
num_policy = "noisy-quantile"
