seed = 6

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.5898939692887321
gamma = 0.1800172987376357
lambda = 0.0
learning_rate = 0.006318252924199271
max_depth = 3
min_child_weight = 3.5640570997027607
subsample = 0.9688559350514705

[fit]
verbose = true

[data]
seed = 0
path = ":data/sberbank-housing"
cache = true
split = "sliding-window-2"
cat_policy = "ordinal"
