seed = 3
patience = 16
n_epochs = -1
causal = false
batch_size = 1024
context_size = 96

[model]
d_main = 128
context_dropout = 0.2803360712432374
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.25955697040798087
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 5.987686373569507e-05
weight_decay = 3.0633048871579933e-06

[data]
seed = 0
path = ":data/delivery-eta"
cache = true
split = "random-2"
cat_policy = "ordinal"
num_policy = "identity"
