seed = 12
patience = 16
n_epochs = -1
batch_size = 256

[model.backbone]
type = "FTTransformerBackbone"
attention_n_heads = 8
ffn_d_hidden_multiplier = 2
ffn_activation = "ReLU"
residual_dropout = 0
n_blocks = 2
d_block = 64
attention_dropout = 0.07024226274304651
ffn_dropout = 0.027444306843997963

[model.num_embeddings]
type = "LinearEmbeddings"

[optimizer]
type = "AdamW"
lr = 0.00029385860066408426
weight_decay = 0.00046633414685389823

[data]
seed = 0
path = ":data/sberbank-housing"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
