seed = 1

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.5688231408705148
gamma = 0
lambda = 0.0
learning_rate = 0.007854114173135678
max_depth = 9
min_child_weight = 91.79811509607913
subsample = 0.88719249089806

[fit]
verbose = true

[data]
seed = 0
path = ":data/delivery-eta"
cache = true
split = "sliding-window-0"
cat_policy = "ordinal"
