seed = 5
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "SNN"
n_blocks = 14
d_block = 2048
dropout = 0.0

[optimizer]
type = "AdamW"
lr = 0.0008182177535058711
weight_decay = 2.8328986258333598e-05

[data]
seed = 0
path = ":data/delivery-eta"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "identity"
