seed = 3
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "DCNv2"
d_cat_embedding = 4
d_deep = 128
n_cross_layers = 1
n_deep_layers = 3
dropout_p = 0.13820799617623797
nonlin_cross = false

[optimizer]
type = "AdamW"
lr = 1.1253175169545924e-05
weight_decay = 6.2723895226860325e-06

[data]
seed = 0
path = ":data/ecom-offers"
cache = true
split = "default"
num_policy = "noisy-quantile"
