seed = 0
function = "bin.nn_baselines.main"
n_trials = 25

[space]
seed = 0
patience = 16
n_epochs = -1
batch_size = 256

[space.model.backbone]
type = "FTTransformerBackbone"
attention_n_heads = 8
ffn_d_hidden_multiplier = 2
ffn_activation = "ReLU"
residual_dropout = 0
n_blocks = [
    "_tune_",
    "int",
    1,
    4,
]
d_block = [
    "_tune_",
    "int-power-of-two",
    5,
    8,
]
attention_dropout = [
    "_tune_",
    "uniform",
    0.0,
    0.5,
]
ffn_dropout = [
    "_tune_",
    "uniform",
    0.0,
    0.5,
]

[space.model.num_embeddings]
type = "LinearEmbeddings"

[space.optimizer]
type = "AdamW"
lr = [
    "_tune_",
    "loguniform",
    1e-05,
    0.001,
]
weight_decay = [
    "_tune_",
    "loguniform",
    1e-06,
    0.001,
]

[space.data]
seed = 0
path = ":data/sberbank-housing"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
