seed = 12
patience = 16
n_epochs = -1
causal = true
batch_size = 1024
context_size = 96

[model]
d_main = 128
context_dropout = 0.4911424119853225
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.2642894789808687
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 5.255072638431167e-05
weight_decay = 0.0004532104808579456

[data]
seed = 0
path = ":data/maps-routing"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "identity"
