seed = 11

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.548169333397524
gamma = 0.001333705437713272
lambda = 0.0
learning_rate = 0.005651512755444466
max_depth = 12
min_child_weight = 67.68798269596647
subsample = 0.9123412128091114

[fit]
verbose = true

[data]
seed = 0
path = ":data/homecredit-default"
cache = true
split = "random-0"
cat_policy = "ordinal"
