seed = 5
patience = 16
n_epochs = -1
causal = false
batch_size = 1024
context_size = 96

[model]
d_main = 512
context_dropout = 0.5355276132458343
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.0
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 0.000589209687450083
weight_decay = 2.229296421808827e-06

[data]
seed = 0
path = ":data/homesite-insurance"
cache = true
split = "random-2"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
