seed = 5

[model]
n_estimators = 4000
stopping_rounds = 3999
device_type = "gpu"
verbose = 2
n_jobs = 4
feature_fraction = 0.5182045593634539
lambda_l2 = 0.0
learning_rate = 0.006702616594080339
num_leaves = 4
min_sum_hessian_in_leaf = 0.0008228805865657352
bagging_fraction = 0.9091621312049262

[fit]

[data]
seed = 0
path = ":data/ecom-offers"
cache = true
split = "default"
