seed = 3

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.9006342056205371
gamma = 0
lambda = 8.260446799517135
learning_rate = 0.0038361713915958276
max_depth = 8
min_child_weight = 0.00036571265886524
subsample = 0.9013901968345776

[fit]
verbose = true

[data]
seed = 0
path = ":data/sberbank-housing"
cache = true
split = "random-2"
cat_policy = "ordinal"
