seed = 8
patience = 16
n_epochs = -1
batch_size = 256

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 256
dropout = 0.7154762957629172

[optimizer]
type = "AdamW"
lr = 0.00014934277964358576
weight_decay = 1.2986548812073137e-06

[data]
seed = 0
path = ":data/sberbank-housing"
cache = true
split = "random-1"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
