seed = 6

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.5204546732195807
gamma = 0
lambda = 0.0
learning_rate = 0.00925218726545299
max_depth = 7
min_child_weight = 0.0009293371268677855
subsample = 0.5550545717385075

[fit]
verbose = true

[data]
seed = 0
path = ":data/maps-routing"
cache = true
split = "default"
cat_policy = "ordinal"
