seed = 13
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 128
dropout = 0.4121166653635105

[optimizer]
type = "AdamW"
lr = 0.00023147219699786348
weight_decay = 9.845825417191035e-06

[data]
seed = 0
path = ":data/cooking-time"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "identity"
