seed = 11
patience = 16
n_epochs = -1
causal = false
batch_size = 256
context_size = 96

[model]
d_main = 128
context_dropout = 0.5021430688659988
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.26831118238489043
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 5.390858530013503e-05
weight_decay = 1.0137573258203974e-06

[data]
seed = 0
path = ":data/sberbank-housing"
cache = true
split = "random-0"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
