seed = 8
patience = 16
n_epochs = -1
batch_size = 256

[model.backbone]
type = "ResNet"
n_blocks = 4
d_block = 1024
d_hidden_multiplier = 2
dropout1 = 0.45364118809588916
dropout2 = 0.447005227343955

[optimizer]
type = "AdamW"
lr = 2.9100190613506918e-05
weight_decay = 1.0002592106213878e-06

[data]
seed = 0
path = ":data/sberbank-housing"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
