seed = 0

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.5277666964731265
gamma = 0.015276454617248563
lambda = 4.829302043079928
learning_rate = 0.013938524169813444
max_depth = 11
min_child_weight = 44.5772110662212
subsample = 0.956194481781763

[fit]
verbose = true

[data]
seed = 0
path = ":data/weather"
cache = true
split = "sliding-window-2"
