seed = 6

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.6535105341042051
gamma = 0
lambda = 3.6376476019433617
learning_rate = 0.0022512436650383885
max_depth = 10
min_child_weight = 0.00022326969051139603
subsample = 0.7139259475679469

[fit]
verbose = true

[data]
seed = 0
path = ":data/sberbank-housing"
cache = true
split = "random-0"
cat_policy = "ordinal"
