seed = 14
patience = 16
n_epochs = -1
batch_size = 1024

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 128
d_embedding = 32
frequency_init_scale = 0.02211333982131203
lite = false

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 2048
dropout = 0.6159849717269967

[optimizer]
type = "AdamW"
lr = 0.0003049239868524141
weight_decay = 0.0003699378445490172

[data]
seed = 0
path = ":data/homesite-insurance"
cache = true
split = "random-2"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
