seed = 9
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "SNN"
n_blocks = 4
d_block = 2048
dropout = 0.3727121756057724

[optimizer]
type = "AdamW"
lr = 0.0005541329593332325
weight_decay = 1.814811848376749e-05

[data]
seed = 0
path = ":data/ecom-offers"
cache = true
split = "default"
num_policy = "noisy-quantile"
