seed = 0
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0

[data]
cache = true
path = "data/sberbank-housing"
num_policy = "noisy-quantile"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.0003
weight_decay = 0.0

[model]
P = 128
d = 128
n_cycles = 6
