seed = 6
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 2048
dropout = 0.7444872069263258

[optimizer]
type = "AdamW"
lr = 1.0674180809519393e-05
weight_decay = 1.829494547326385e-06

[data]
seed = 0
path = ":data/maps-routing"
cache = true
split = "random-1"
cat_policy = "ordinal"
num_policy = "identity"
