seed = 2
patience = 16
n_epochs = -1
causal = false
batch_size = 1024
context_size = 96

[model]
d_main = 256
context_dropout = 0.5911269197264194
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.012783249291032694
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 3.027182571350983e-05
weight_decay = 8.607626638194285e-06

[data]
seed = 0
path = ":data/homecredit-default"
cache = true
split = "random-2"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
