seed = 4
patience = 16
n_epochs = -1
batch_size = 256

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 32
d_embedding = 4
frequency_init_scale = 0.02302327697934275
lite = false

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 256
dropout = 0.7162715257838813

[optimizer]
type = "AdamW"
lr = 0.0002994680757366253
weight_decay = 5.369437236660391e-06

[data]
seed = 0
path = ":data/sberbank-housing"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
