seed = 5
patience = 16
n_epochs = -1
causal = true
batch_size = 1024
context_size = 96

[model]
d_main = 256
context_dropout = 0.49595980579801563
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.3906238710627897
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 0.000609022702151379
weight_decay = 1.4148374603515379e-06

[data]
seed = 0
path = ":data/homesite-insurance"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
