seed = 7
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 128
dropout = 0.3807332561417784

[optimizer]
type = "AdamW"
lr = 9.39605216140724e-05
weight_decay = 0.0002004963983765288

[data]
seed = 0
path = ":data/delivery-eta"
cache = true
split = "random-0"
cat_policy = "ordinal"
num_policy = "identity"
