seed = 12

[model]
iterations = 4000
early_stopping_rounds = 3999
od_pval = 0.001
bagging_temperature = 0.2915161396867666
depth = 8
l2_leaf_reg = 9.61485241767876
leaf_estimation_iterations = 1
learning_rate = 0.03281911891834306
task_type = "CPU"
thread_count = 4

[fit]
logging_level = "Verbose"

[data]
seed = 0
path = ":data/maps-routing"
cache = true
split = "default"
cat_policy = "ordinal"
