seed = 6

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.5093205328041808
gamma = 0.1916906406712451
lambda = 0.5745245774199953
learning_rate = 0.010302865638216521
max_depth = 6
min_child_weight = 0.06888916070116458
subsample = 0.822054691903473

[fit]
verbose = true

[data]
seed = 0
path = ":data/maps-routing"
cache = true
split = "random-0"
cat_policy = "ordinal"
