seed = 6
patience = 16
n_epochs = -1
causal = false
batch_size = 1024
context_size = 96

[model]
d_main = 256
context_dropout = 0.5957054584993395
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.43409493610931826
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 0.0003666594732803351
weight_decay = 1.4179168866038854e-06

[data]
seed = 0
path = ":data/ecom-offers"
cache = true
split = "sliding-window-0"
num_policy = "noisy-quantile"
