seed = 14

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.7269659356283817
gamma = 0
lambda = 0.0
learning_rate = 0.010230517475027552
max_depth = 9
min_child_weight = 6.629579347086336
subsample = 0.9551763483176675

[fit]
verbose = true

[data]
seed = 0
path = ":data/delivery-eta"
cache = true
split = "default"
cat_policy = "ordinal"
