seed = 6
patience = 16
n_epochs = -1
batch_size = 1024

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 8
d_embedding = 8
frequency_init_scale = 0.010337105799304436
lite = false

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 2048
dropout = 0.0

[optimizer]
type = "AdamW"
lr = 3.6367718912371575e-05
weight_decay = 0.0002329134581689813

[data]
seed = 0
path = ":data/maps-routing"
cache = true
split = "random-0"
cat_policy = "ordinal"
num_policy = "identity"
