seed = 14
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "DCNv2"
d_cat_embedding = 2
d_deep = 512
n_cross_layers = 2
n_deep_layers = 2
dropout_p = 0.14075547676630562
nonlin_cross = false

[optimizer]
type = "AdamW"
lr = 0.0008572096658852447
weight_decay = 0.00018852506498640324

[data]
seed = 0
path = ":data/weather"
cache = true
split = "default"
num_policy = "noisy-quantile"
