seed = 8

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.9077791871421083
gamma = 0.6046121705881746
lambda = 1.640750219752763
learning_rate = 0.015268497342854133
max_depth = 5
min_child_weight = 0.009752293006969694
subsample = 0.8371230479564767

[fit]
verbose = true

[data]
seed = 0
path = ":data/homesite-insurance"
cache = true
split = "sliding-window-1"
cat_policy = "ordinal"
