seed = 9
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 512
dropout = 0.6890006338722113

[optimizer]
type = "AdamW"
lr = 1.3216010452287834e-05
weight_decay = 0.0005543892307831469

[data]
seed = 0
path = ":data/homecredit-default"
cache = true
split = "random-1"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
