seed = 4

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.5090022237779552
gamma = 0
lambda = 6.06763906295072
learning_rate = 0.005300366576413499
max_depth = 9
min_child_weight = 0.0035484569329249714
subsample = 0.8159379211373473

[fit]
verbose = true

[data]
seed = 0
path = ":data/cooking-time"
cache = true
split = "random-0"
cat_policy = "ordinal"
