seed = 13
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "SNN"
n_blocks = 1
d_block = 256
dropout = 0.41094045911480265

[optimizer]
type = "AdamW"
lr = 5.195098215968876e-05
weight_decay = 0.0008985521729065786

[data]
seed = 0
path = ":data/homecredit-default"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
