seed = 6
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 128
dropout = 0.0

[optimizer]
type = "AdamW"
lr = 0.00012326374476649522
weight_decay = 3.830273601780913e-05

[data]
seed = 0
path = ":data/ecom-offers"
cache = true
split = "default"
num_policy = "noisy-quantile"
