seed = 14

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.5634926299587952
gamma = 0.08010779174593262
lambda = 0.0
learning_rate = 0.005501108827208121
max_depth = 12
min_child_weight = 36.05674927111959
subsample = 0.6265121231167744

[fit]
verbose = true

[data]
seed = 0
path = ":data/homecredit-default"
cache = true
split = "sliding-window-2"
cat_policy = "ordinal"
