seed = 13
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 256
dropout = 0.44332285293376333

[optimizer]
type = "AdamW"
lr = 0.0006027615107557518
weight_decay = 3.3245570426097075e-05

[data]
seed = 0
path = ":data/ecom-offers"
cache = true
split = "random-1"
num_policy = "noisy-quantile"
