seed = 11
batch_size = 1024
patience = 16
n_epochs = -1

[data]
seed = 0
cache = true
path = ":data/ecom-offers"
num_policy = "noisy-quantile"

[model]
P = 128
d = 128
n_cycles = 6

[optimizer]
type = "AdamW"
lr = 0.0003
weight_decay = 0.0
