seed = 4
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 128
dropout = 0.0

[optimizer]
type = "AdamW"
lr = 9.590352503838162e-05
weight_decay = 5.532816552562479e-05

[data]
seed = 0
path = ":data/ecom-offers"
cache = true
split = "sliding-window-1"
num_policy = "noisy-quantile"
