seed = 13

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.9440430836985381
gamma = 0.0043254513908357935
lambda = 0.0
learning_rate = 0.005114436280949988
max_depth = 7
min_child_weight = 0.12309068059451692
subsample = 0.6659060266708797

[fit]
verbose = true

[data]
seed = 0
path = ":data/ecom-offers"
cache = true
split = "random-2"
