seed = 8
patience = 16
n_epochs = -1
causal = true
batch_size = 1024
context_size = 96

[model]
d_main = 256
context_dropout = 0.5963515305838978
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.02329375762584318
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 1.3654877472144522e-05
weight_decay = 0.00014321565608576

[data]
seed = 0
path = ":data/homecredit-default"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
