seed = 8
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 256
dropout = 0.7366642437430879

[optimizer]
type = "AdamW"
lr = 9.564233127760087e-05
weight_decay = 3.750581700073781e-05

[data]
seed = 0
path = ":data/homesite-insurance"
cache = true
split = "random-2"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
