seed = 2
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 128
dropout = 0.13707857301666926

[optimizer]
type = "AdamW"
lr = 5.175770841107558e-05
weight_decay = 0.00040469480007836243

[data]
seed = 0
path = ":data/delivery-eta"
cache = true
split = "random-1"
cat_policy = "ordinal"
num_policy = "identity"
