seed = 7
patience = 16
n_epochs = -1
causal = false
batch_size = 1024
context_size = 96

[model]
d_main = 1024
context_dropout = 0.4660758688837844
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.22945207007380758
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 0.0002685363826034026
weight_decay = 1.8956225523262226e-06

[data]
seed = 0
path = ":data/ecom-offers"
cache = true
split = "sliding-window-1"
num_policy = "noisy-quantile"
