seed = 11

[model]
n_estimators = 4000
stopping_rounds = 3999
device_type = "gpu"
verbose = 2
n_jobs = 4
feature_fraction = 0.5230469680384683
lambda_l2 = 0.0
learning_rate = 0.012146575761249246
num_leaves = 553
min_sum_hessian_in_leaf = 0.4580718686399595
bagging_fraction = 0.6124445780966243

[fit]

[data]
seed = 0
path = ":data/weather"
cache = true
split = "default"
