seed = 0

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.8426072124923818
gamma = 0.0772697061895549
lambda = 0.31975732203397794
learning_rate = 0.003657882344985462
max_depth = 9
min_child_weight = 0.09501663648641442
subsample = 0.6064233828528467

[fit]
verbose = true

[data]
seed = 0
path = ":data/cooking-time"
cache = true
split = "default"
cat_policy = "ordinal"
