seed = 2

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.6920019572766726
gamma = 0
lambda = 0.0
learning_rate = 0.006690247818254889
max_depth = 8
min_child_weight = 0.6806566691582743
subsample = 0.885433482775677

[fit]
verbose = true

[data]
seed = 0
path = ":data/cooking-time"
cache = true
split = "default"
cat_policy = "ordinal"
