seed = 3
patience = 16
n_epochs = -1
causal = false
batch_size = 256
context_size = 96

[model]
d_main = 256
context_dropout = 0.20871452834454793
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.2930768928408447
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 5.5978560047031827e-05
weight_decay = 2.314547621852438e-05

[data]
seed = 0
path = ":data/sberbank-housing"
cache = true
split = "sliding-window-1"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
