seed = 12

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.5122319826891414
gamma = 0.005623741867481477
lambda = 4.607130343709838
learning_rate = 0.007356488597901895
max_depth = 8
min_child_weight = 81.83532926879022
subsample = 0.8200447023155237

[fit]
verbose = true

[data]
seed = 0
path = ":data/maps-routing"
cache = true
split = "sliding-window-0"
cat_policy = "ordinal"
