seed = 11
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 2048
dropout = 0.1256263645250478

[optimizer]
type = "AdamW"
lr = 0.0008948041773884203
weight_decay = 0.000260781835357732

[data]
seed = 0
path = ":data/delivery-eta"
cache = true
split = "sliding-window-2"
cat_policy = "ordinal"
num_policy = "identity"
