seed = 2

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.5300113744650279
gamma = 0
lambda = 0.5626717601514345
learning_rate = 0.006895319290127187
max_depth = 10
min_child_weight = 19.874603496910964
subsample = 0.9881639983478234

[fit]
verbose = true

[data]
seed = 0
path = ":data/homesite-insurance"
cache = true
split = "random-0"
cat_policy = "ordinal"
