seed = 1
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 256
dropout = 0.12286696666604158

[optimizer]
type = "AdamW"
lr = 0.0005269574687816383
weight_decay = 0.00010891070755267712

[data]
seed = 0
path = ":data/weather"
cache = true
split = "default"
num_policy = "noisy-quantile"
