seed = 8
patience = 16
n_epochs = -1
causal = false
batch_size = 1024
context_size = 96

[model]
d_main = 1024
context_dropout = 0.4685316216314625
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.0
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 0.00020330766509412082
weight_decay = 0.0004794604209794534

[data]
seed = 0
path = ":data/ecom-offers"
cache = true
split = "default"
num_policy = "noisy-quantile"
