seed = 11
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 2048
dropout = 0.0

[optimizer]
type = "AdamW"
lr = 0.0003914756765406393
weight_decay = 0.0007184000062271937

[data]
seed = 0
path = ":data/weather"
cache = true
split = "sliding-window-1"
num_policy = "noisy-quantile"
