seed = 4
patience = 16
n_epochs = -1
batch_size = 1024

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 2048
dropout = 0.0

[optimizer]
type = "AdamW"
lr = 1.829373417942218e-05
weight_decay = 0.0002102261023106899

[data]
seed = 0
path = ":data/homecredit-default"
cache = true
split = "random-2"
cat_policy = "ordinal"
num_policy = "noisy-quantile"
