seed = 7

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.5009783174384482
gamma = 0.010107146894548526
lambda = 4.301365025839507
learning_rate = 0.013717345902389553
max_depth = 10
min_child_weight = 8.283133320015851
subsample = 0.998164843245853

[fit]
verbose = true

[data]
seed = 0
path = ":data/weather"
cache = true
split = "default"
