seed = 0
function = "bin.tabr.main"
n_trials = 25

[space]
seed = 0
patience = 16
n_epochs = -1
causal = true
batch_size = 1024
context_size = 96

[space.model]
d_main = [
    "_tune_",
    "int-power-of-two",
    7,
    10,
]
context_dropout = [
    "_tune_",
    "?uniform",
    0.0,
    0.0,
    0.6,
]
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = [
    "_tune_",
    "?uniform",
    0.0,
    0.0,
    0.6,
]
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[space.optimizer]
type = "AdamW"
lr = [
    "_tune_",
    "loguniform",
    1e-05,
    0.001,
]
weight_decay = [
    "_tune_",
    "loguniform",
    1e-06,
    0.001,
]

[space.data]
seed = 0
path = ":data/cooking-time"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "identity"
