seed = 0

[model]
booster = "gbtree"
n_estimators = 4000
early_stopping_rounds = 3999
n_jobs = 1
tree_method = "hist"
device = "cuda"
use_label_encoder = false
colsample_bytree = 0.5001884399199125
gamma = 0.01792974194603026
lambda = 0.0
learning_rate = 0.0034111591716618596
max_depth = 11
min_child_weight = 0.6697591311432322
subsample = 0.6314475686976316

[fit]
verbose = true

[data]
seed = 0
path = ":data/cooking-time"
cache = true
split = "random-2"
cat_policy = "ordinal"
