seed = 3
patience = 16
n_epochs = -1
causal = true
batch_size = 1024
context_size = 96

[model]
d_main = 128
context_dropout = 0.5107174749212559
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.5044892059823758
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 5.73605507046113e-05
weight_decay = 5.979008768608573e-05

[data]
seed = 0
path = ":data/cooking-time"
cache = true
split = "default"
cat_policy = "ordinal"
num_policy = "identity"
